### ISSUE TITLE
border-radius not working for .post-thumb

### ISSUE THREAD

**Issue by raduchiriac** [SalGnt/Travelogue#8]
I have an Android 5.0.2 using the latest Chrome and the `.post-thumb` does not have any border-radius when you go inside a post. 

This has - of course nothing to do with the code quality of "Travelogue", it's a general CSS issue on Androids, I guess. For the moment I fixed this by reducing the width/height of the `<img />` for mobile only

``` css
@include media-query($on-palm) {
  width: 160px;
  height: 160px;
}
```
